# Generated by Django 5.2.6 on 2025-09-29 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobchangelog',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='ops.job'),
        ),
        migrations.AddField(
            model_name='jobchangelog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ops.job'),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='required_equipment',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='ops.equipment'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'scheduled_date'], name='jobs_status_43ffea_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['assigned_to', 'status'], name='jobs_assigne_1473c3_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['overdue', 'status'], name='jobs_overdue_6d074e_idx'),
        ),
        migrations.AddIndex(
            model_name='jobchangelog',
            index=models.Index(fields=['job', '-timestamp'], name='job_change__job_id_2fb8a8_idx'),
        ),
        migrations.AddIndex(
            model_name='jobtask',
            index=models.Index(fields=['job', 'status'], name='job_tasks_job_id_9583e4_idx'),
        ),
        migrations.AddIndex(
            model_name='jobtask',
            index=models.Index(fields=['job', 'order'], name='job_tasks_job_id_c2623b_idx'),
        ),
    ]
